### PR TITLE
开源之夏：MegEngine 补充跨模态模型的实现——DALL-E

### PR DESCRIPTION
**Pull request by Asthestarsfalll**
参考实现：[DALLE-pytorch](https://github.com/lucidrains/DALLE-pytorch) [DALL-E](https://github.com/openai/DALL-E)

- [x] OpenaiDicreteVAE编写
- [x] OpenaiDicreteVAE与训练权重转换
- [x] OpenaiDicreteVAE对齐
- [x] Attention编写
- [x] Attention对齐
- [x] SparseConvolutionAttention编写
- [x] SparseConvolutionAttention对齐
- [x] SparseAxialAttention编写
- [x] SparseAxialAttention对齐
- [x] Transformer编写
- [x] Transformer对齐
- [x] DALLE编写
- [x] DALLE对齐
- [x] 其他对齐
- [x] 推理结果
- [x] 文档
- [x] 添加其他vae模型

### CODE REVIEW

**Comment by Zhiy-Zhang** [comment]
LGTM

**Comment by Asthestarsfalll** [comment]
推理结果：
total

**Comment by Asthestarsfalll** [comment]
> reference: [lucidrains/DALLE-pytorch#335](https://github.com/lucidrains/DALLE-pytorch/discussions/335)

已添加在dalle文件夹下的README中

**Comment by Zhiy-Zhang** [comment]
> > reference: [lucidrains/DALLE-pytorch#335](https://github.com/lucidrains/DALLE-pytorch/discussions/335)
> 
> 已添加在dalle文件夹下的README中

ok,看到了

**Pull request merged**
